### ISSUE TITLE
stress testing

### ISSUE THREAD

**Issue by sblig** [brookshi/Hitchhiker-Node#2]
There is no valid Hitchhiker-Node, please run a Hitchhiker-Node first.

**Comment by brookshi** [comment]
做压力测试需要先运行一个Hitchhiker-Node，在www.hitchhiker-api.com上面没有部署 Hitchhiker-Node，虚拟机性能吃不消，所以就没有这块的演示了。
想用的话可以部署到本地，另外正在开发另一套基于Node的压力测试，这个方便些，不依赖Hitchhiker-Node了

**Comment by yuefenglovegithub** [comment]
win_64 和 osx_64运行起来都报 
info: 2018/01/16 15:21:07 main.go:12: set max procs:  8
info: 2018/01/16 15:21:07 client.go:51: read config
info: 2018/01/16 15:21:07 client.go:66: connect: success
info: 2018/01/16 15:21:07 client.go:120: send request run result 0
info: 2018/01/16 15:21:07 client.go:68: status: idle
error: 2018/01/16 15:21:07 client.go:83: read: EOF
错误，请问这个该如何解决，已经修改配置的ip
